services:
  - type: web
    name: docplus-backend
    env: node
    buildCommand: cd new-backend && npm install
    startCommand: cd new-backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  - type: web
    name: docplus-frontend
    env: node
    buildCommand: |
      cd frontend && 
      npm install && 
      npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4173