services:
  - type: web
    name: docplus
    env: node
    runtime: node
    runtimeVersion: "22.14.0"
    buildCommand: |
      npm install
      cd frontend
      npm install
      npm run build
      cd ../new-backend
      npm install
    startCommand: cd new-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_SECRET_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_CLERK_SECRET_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: VITE_ALLOWED_DOMAINS
        sync: false
      - key: VITE_APP_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VITE_BACKEND_URL
        sync: false