services:
  - type: web
    name: docplus
    env: node
    buildCommand: |
      npm install
      cd frontend
      npm install
      npm run build
      cd ../new-backend
      npm install
    startCommand: cd new-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false